import Head from "next/head";
import styles from "@/styles/Home.module.css";
import ShowCase from "../pages/showcase";
import AboutHome from '../pages/about-home'
import StartNow from './our-program'
import VirtualTour from '../pages/virtual-tour'
import Testimonials from '../pages/testimonials'
import Events from '../pages/event-home';
import Footer from '../pages/footer'

function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ShowCase />
        <AboutHome/>
        <StartNow />
        <VirtualTour/>
        <Testimonials/>
        <Events/>
        <Footer/>
      </div>
    </>
  );
}
export default  Home